FROM python:3.10.12-alpine 

WORKDIR /app

# Install pipenv and compilation dependencies
RUN pip install pipenv

# Install python dependencies in /.venv
COPY Pipfile .
COPY Pipfile.lock .
ENV PIPENV_VENV_IN_PROJECT=1 
RUN pipenv install --deploy

ENV PATH="/.venv/bin:$PATH"

# Install application into container
COPY . .
RUN chmod +x ./app.py

# Run the migrations against the database
ENTRYPOINT ["pipenv", "run", "migrate"]
